# Generated by Django 3.0.6 on 2020-05-07 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('lat', models.FloatField(max_length=5)),
                ('lon', models.FloatField(max_length=5)),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
